name: dry-auto_inject
gemspec:
  authors: ["Piotr Solnica"]
  email: ["piotr.solnica@gmail.com"]
  summary: "Container-agnostic automatic constructor injection"
  development_dependencies:
    - bundler
    - rake
    - rspec
  runtime_dependencies:
    - [dry-core, "~> 1.0", "< 2"]
    - [zeitwerk, "~> 2.6"]
